### ISSUE TITLE
Im Hands-on UI laden Filme nicht mehr

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#358]
Im Hands-on-UI scheinen seit kurzem Filme nicht mehr korrekt zu laden.

Anthon Astrom von Astrom Zimmer, der das UI mitprogramiert hat, schrieb folgendes:
> The requests to MAdeK return video for a while, then stops, without even a timeout (normally a server sends a “timeout” response after ~30s). 
I’m wondering if it’s a policy thing (i.e. many requests from the same IP) or simply an overload problem (i.e. just too many requests for the server to handle).

![image](https://user-images.githubusercontent.com/42544602/133474160-0065d349-b9c7-4763-a2a1-0ea4c6f97d13.png)

Was braucht es, um der Ursache auf den Grund zu kommen?

**Comment by phoettli** [comment]
ok, Anthon schreibt weiter:

> I’ll jump in here, since I guess that’s faster:

> It’s very simple: At some point after navigating the web app the video requests stop returning responses, and at that point it doesn’t/didn’t matter if the requests were XHR or HTTP requests (i.e. direct browser access) – the assets were simply not loading.
> I can’t reproduce the issue anymore, either (Günz, chime in if you still can). But if you could ask the developers to check the logs between 2pm and 4pm today (that’s when Michael reported the issue, and I could reproduce it), that would be great. Unless there’s some throttling happening, I suspect an overload issue.

**Comment by phoettli** [comment]
... und

> My bad, forgot to include an example URL: https://medienarchiv.zhdk.ch/media/2422cf2c-e7b7-4bb8-a05f-8c53fb098419

> I didn’t check any images, only video, but all requests to https://medienarchiv.zhdk.ch/media/<UID> were unresponsive.

> Let me know if there’s anything else I can help with.

**Comment by DrTom** [comment]
There are no general or to the ticket specific timeouts in the given time range visible in the server logs. 

However, there are timeouts close to the time range specific to the `/upload` resource. DOS problems related to uploads are known problem and are addressed with a currently ongoing project. 

Such timeouts could also be caused by network problems and might not show in the server logs then. 

Please create a new issue if this problem arises again in particular if it can be reproduced. Also please supply a more precise timestamp when the incident occured in the future.

**Comment by eins78** [comment]
I also could not find any indication of an "overload" problem in the logs: in the timespan mentioned there are many requests to the example URL (all with status `206` or `200`) and also many other sucessfull requests at the same time.
A complete overload of the server is possible but would be detected by our monitoring system.

From the provided information there is nothing else we can debug server-side, as it is not even clear if the requests are pending in the client or "on the wire". Request with state "pending" can also be caused by brower extensions (like ad blocker) or antivirus software on the system.

Questions to answer in case this happens again:
* do request to other host go through?
* do requests go through in another chrome tab?
* do request go through when using `curl` on the command line?
Also, there might be more information in the chrome network logs: https://support.google.com/chrome/a/answer/6271171?hl=en#zippy=%2Cview-network-data%2Cget-network-logs

**Comment by phoettli** [comment]
von Günz bestätigt:

Am 27. Juli wurden die letzten Medien hochgeladen und das UI getestet.
Geschwindigkeit: **eher langsam oder so wie jetzt**

Vor dem Update lief es nicht überragend schnell, aber OK.

Am letzten Montag, 13.9. haben dann die Filme nicht mehr geladen bei drei verschiedenen Personen an drei verschiedenen Orten in Zürich, an der ZHdK und Innerschweiz.
 
> I clicked this at 14:14:30 today (monday 13.9.). The resources where here fast (see screenshot) , 
> the film ist still loading at 14:17:30, so 3 minutes later-
> https://hands-on.azt.pink/residency_HO_3/s=min;c=materials/s=min;z=0.01/play=1608195545?materials_ids=mate_HO_341
> 
> Same here, clicked 14:18:15:
> https://hands-on.azt.pink/residency_HO_3/s=min;c=materials/s=min;z=0.01/play=1611043505?materials_ids=mate_HO_355
> Still loading 3 minutes later…..
> 
> or here:
> https://hands-on.azt.pink/residency_HO_2/s=min;c=materials/s=max;z=0.01/play=1578386169?materials_ids=mate_HO_355
> same-
 
Seit Montag, 13.9. laden die Medien einzelner Seiten immer mal wieder korrekt und dann wieder nur teilweise oder überhaupt nicht. Freitag 17.9. mehrere Fehlaufrufe rapportiert:
 
Beim ersten sind erst nach ca. 2 Minuten die Videos erschienen:
> https://hands-on.azt.pink/residency_HO_3/s=min;c=index/s=min;z=0.01/play=1611054784
> I clicked on it at 10:18:21
> 10:20:07 until the first movie showed up
> 10:20:24 until the second movie showed up.
 
Beim zweiten wurden die Videos überhaupt nicht geladen und nach 5 Minuten wurde der Ladeprozess abgebrochen:
> https://hands-on.azt.pink/residency_HO_3/s=min;c=materials/s=min;z=0.01/play=1608213743?materials_ids=mate_HO_341
> Clicked on it today at 10:27:30,
> At 10:30:30 still nothing happening.
> 10:32:50 nothing, no more loading activity
 
Zwischen dem 27.7. und dem 13.9. wurde das UI nicht mehr getestet.
 
_Vor dem letzten Upload üblich, dass die Videos auf diesen Seiten bis ca. 2 Minuten zum Laden benötigen? Oder wie lange dauerte die Ladezeit dann?_

`Vor dem laden dauerte es jeweils max 30 Sekunden. Auf verschiedenen alten Computern z.T. länger. Ich habe immer auf demselben ZHdK Macbook von 2019 gearbeitet.`

_Wenn einmal Filme nicht laden, laden sie dann, wenn du den Reload-Button am Browser drückst?_

**Eben getestet mit dem Link vom ersten Mail: Ja.
D.h Link eingegeben. UI ist hängengeblieben. Dann reload: es läuft.**

**Comment by phoettli** [comment]
Entwickler schreibt:

> After a quick click-around and a Google search, I think I’ve isolated the problem:
It’s a browser issue. When ~3 (depending on browser, but seems to be around 3) videos are simultaneously loading in the background, the subsequent video(s) will be prevent from loading with a ’stalled' error event fired. On Chrome those requests still show up as “pending”, while on Firefox they don’t show up at all (which is more accurate in some ways, since those requests are in fact never sent to the server). We use Chrome for testing, hence the inaccurate assumption that the problem lay at API level. 

> **I apologise for the extra hassle.**

> Günz: Since this has been standard behaviour in browsers since the introduction of the <Video/> element, and thus this problem has been around since the start of the project, what changed in July must have been the way you use/test the app. So just refresh the page if this happens (since we use URL state, refreshing the page won’t throw you out of your current view). If there’s time in Oct, we’ll have a look to see if there’s anything we can do to prevent it in the app code itself.

**Comment by phoettli** [comment]
Danke euch für die Unterstützung !
